"""10 core card templates + 10 Christmas templates."""

TEMPLATES = [
    {"id": "thought_bubble", "name": "Human Crisis / Pet Priority", "family": "contrast",
     "description": "Human worried about something serious. Pet thinking about something trivial.",
     "required": ["pet_image", "recipient_name"], "optional": ["job", "current_anxiety"],
     "text_slots": ["headline", "punchline"], "image_slots": ["pet_image", "owner_image"]},
    {"id": "pet_standup", "name": "Pet Stand-Up", "family": "status_inversion",
     "description": "Pet at a microphone roasting the owner.",
     "required": ["pet_image", "recipient_name"], "optional": ["facts"],
     "text_slots": ["headline", "punchline"], "image_slots": ["pet_image"]},
    {"id": "breaking_news", "name": "Breaking News", "family": "documentary",
     "description": "Fake news broadcast about the recipient.",
     "required": ["recipient_name"], "optional": ["pet_image", "embarrassing_fact"],
     "text_slots": ["headline", "punchline", "subhead"], "image_slots": []},
    {"id": "performance_review", "name": "Pet Performance Review", "family": "status_inversion",
     "description": "Pet evaluates owner like an employee.",
     "required": ["pet_image", "recipient_name"], "optional": ["job", "facts"],
     "text_slots": ["headline", "punchline", "categories"], "image_slots": ["pet_image"]},
    {"id": "pet_therapist", "name": "Pet Therapist", "family": "status_inversion",
     "description": "Pet diagnoses the owner's problems.",
     "required": ["pet_image", "recipient_name"], "optional": ["anxiety_topics"],
     "text_slots": ["headline", "punchline", "diagnosis"], "image_slots": ["pet_image"]},
    {"id": "search_history", "name": "Pet Search History", "family": "observation",
     "description": "Browser search queries from the pet's perspective.",
     "required": ["pet_image", "recipient_name"], "optional": ["facts"],
     "text_slots": ["headline", "searches"], "image_slots": ["pet_image"]},
    {"id": "complaint_dept", "name": "Pet Complaint Department", "family": "status_inversion",
     "description": "Pet files official complaint about the owner.",
     "required": ["pet_image", "recipient_name"], "optional": ["habits", "facts"],
     "text_slots": ["headline", "punchline", "complaint_number"], "image_slots": ["pet_image"]},
    {"id": "split_panel", "name": "Human vs Pet Priorities", "family": "contrast",
     "description": "Split-screen: human concern vs pet interpretation.",
     "required": ["pet_image", "recipient_name"], "optional": ["job", "current_anxiety"],
     "text_slots": ["human_line", "pet_line"], "image_slots": ["pet_image"]},
    {"id": "incident_report", "name": "Official Incident Report", "family": "documentary",
     "description": "Government/workplace incident report about the recipient.",
     "required": ["recipient_name"], "optional": ["pet_image", "age"],
     "text_slots": ["headline", "punchline", "incident_number"], "image_slots": []},
    {"id": "wildcard", "name": "Wildcard Roast", "family": "mixed",
     "description": "Upload your pet. We choose the funniest format.",
     "required": ["pet_image", "recipient_name", "facts"], "optional": [],
     "text_slots": ["headline", "punchline"], "image_slots": ["pet_image"]},
    {"id": "xmas_santa_automated", "name": "Santa Automated", "family": "status_inversion",
     "description": "Santa reads a notice that his role has been automated.",
     "required": ["recipient_name"], "optional": ["pet_image"],
     "text_slots": ["headline", "body", "inside_copy"], "image_slots": ["pet_image", "santa_image"],
     "occasions": ["christmas"], "tags": ["ai", "agi", "automation", "christmas"]},
    {"id": "xmas_santa_vs_robots", "name": "Santa vs Robots", "family": "documentary",
     "description": "Breaking news: robots disabled in sleigh-based attack.",
     "required": ["recipient_name"], "optional": ["pet_image"],
     "text_slots": ["headline", "subhead", "punchline"], "image_slots": ["pet_image"],
     "occasions": ["christmas"], "tags": ["ai", "robots", "christmas"]},
    {"id": "xmas_elf_redundancy", "name": "Elf Redundancy Notice", "family": "corporate",
     "description": "Fake corporate memo: North Pole restructuring after agent deployment.",
     "required": ["recipient_name"], "optional": ["pet_image"],
     "text_slots": ["headline", "body", "footer"], "image_slots": ["pet_image"],
     "occasions": ["christmas"], "tags": ["ai", "work", "christmas"]},
    {"id": "xmas_pet_security", "name": "Pet Security Failure", "family": "observation",
     "description": "Stranger entered via chimney. Dog accepted biscuit. Investigation closed.",
     "required": ["recipient_name"], "optional": ["pet_image"],
     "text_slots": ["headline", "body", "verdict"], "image_slots": ["pet_image"],
     "occasions": ["christmas"], "tags": ["pets", "christmas"]},
    {"id": "xmas_performance_review", "name": "Christmas Performance Review", "family": "corporate",
     "description": "Pet reviews human's Christmas performance.",
     "required": ["recipient_name"], "optional": ["pet_image"],
     "text_slots": ["headline", "categories", "punchline"], "image_slots": ["pet_image"],
     "occasions": ["christmas"], "tags": ["christmas"]},
    {"id": "xmas_human_vs_pet", "name": "Human vs Pet Christmas", "family": "contrast",
     "description": "Human existential Christmas worry vs pet food focus.",
     "required": ["recipient_name"], "optional": ["pet_image"],
     "text_slots": ["human_line", "pet_line"], "image_slots": ["pet_image"],
     "occasions": ["christmas"], "tags": ["ai", "pets", "christmas"]},
    {"id": "xmas_cat_vs_tree", "name": "Cat vs Christmas Tree", "family": "documentary",
     "description": "Incident report: decorative structure destroyed 14 minutes after deployment.",
     "required": ["recipient_name"], "optional": ["pet_image"],
     "text_slots": ["headline", "body", "damage_report"], "image_slots": ["pet_image", "tree_image"],
     "occasions": ["christmas"], "tags": ["cats", "christmas"]},
    {"id": "xmas_santa_search_history", "name": "Santa Reads Search History", "family": "observation",
     "description": "Santa looks horrified while pet looks smug.",
     "required": ["recipient_name"], "optional": ["pet_image"],
     "text_slots": ["headline", "searches", "reaction"], "image_slots": ["pet_image", "santa_image"],
     "occasions": ["christmas"], "tags": ["christmas"]},
    {"id": "xmas_ai_card", "name": "AI Christmas Card", "family": "meta",
     "description": "Human worries about AGI Christmas. Pet points out the card is from an AI.",
     "required": ["recipient_name"], "optional": ["pet_image"],
     "text_slots": ["human_line", "pet_line"], "image_slots": ["pet_image"],
     "occasions": ["christmas"], "tags": ["ai", "agi", "christmas"]},
    {"id": "xmas_pet_complaint", "name": "Pet North Pole Complaint", "family": "status_inversion",
     "description": "Pet writes to Santa requesting replacement owner.",
     "required": ["recipient_name"], "optional": ["pet_image"],
     "text_slots": ["headline", "body", "signature"], "image_slots": ["pet_image"],
     "occasions": ["christmas"], "tags": ["pets", "christmas"]},
]

TEMPLATE_MAP = {t["id"]: t for t in TEMPLATES}

def select_template(facts, occasion):
    text = " ".join(facts).lower()
    if occasion == "christmas":
        if any(k in text for k in ("agi", "ai", "replace", "automation")):
            return "xmas_ai_card"
        return "xmas_santa_automated"
    if occasion == "birthday" and any(c.isdigit() for f in facts for c in f):
        return "incident_report"
    if any(k in text for k in ("agi", "replace", "worry", "stress")):
        return "thought_bubble"
    if any(k in text for k in ("work", "job", "office", "manager")):
        return "performance_review"
    return "pet_standup"
